# ベースイメージとしてGoの公式イメージを使用
FROM golang:1.20

# パッケージの更新と必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
    curl \
    git \
    wget \
    && apt-get clean

# 必要なパッケージをインストールし、依存関係を取得
RUN apk add --no-cache git && \
    go get github.com/agiledragon/gomonkey/v2
    