name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Build Docker image
        run: docker build -f Dockerfile.ci -t unittest .

      - name: Run tests inside Docker container and Unittest
        run: |
          docker run --rm -v ${{ github.workspace }}:/server --name unittest unittest /bin/bash -c "\
            echo 'Listing /server directory:' && \
            cd /server && \
            echo "DOCKER_CLIENT=${{ vars.DOCKER_CLIENT }}" >> .env && \
            echo "LOCALDBSOURCE=${{ vars.LOCALDBSOURCE }}" >> .env && \
            echo "REACT_CLIENT=${{ vars.REACT_CLIENT }}" >> .env && \
            echo "VUE_CLIENT=${{ vars.VUE_CLIENT }}" >> .env && \
            echo "TEST=${{ vars.TEST }}" >> .env && \
            echo '.env content:' && cat .env && \
            chmod +x ./go_test.sh && \
            echo "================= test start ================= && \
            ./go_test.sh && \
            echo "================= test end ================="
